# TODO: Enter all team names to scrape, each on its own line in quotes. Ensure that the names match the official team names listed on the ESPN website.
teams_to_scrape:
  - "Duke Blue Devils"
  - "North Carolina Tar Heels"
  - "UConn Huskies"

# TODO: Set the cutoff date in MM/DD/YYYY format (the scraper will collect data from the start of the current season up to the specified date).
cutoff_date: "01/08/2025"

# TODO: Choose the numerical stats to pull and add them to 'stats_to_pull', each on its own line in quotes. Available options include:
# min, fgm, fga, 2pm, 2pa, 3pm, 3pa, ftm, fta, oreb, dreb, reb, ast, stl, blk, to, pf, pts
stats_to_pull:
  - "pts"
  - "ast"
  - "reb"
  - "min"
  - "blk"
  - "stl"